In [2]:
import pandas as pd
import numpy as np
import sklearn


In [3]:
ninds = 30
nsnps = 5000

In [4]:
# generate a data set with structure
pop1 = np.random.binomial(1, 0.5, (1, nsnps))
pop2 = np.random.binomial(1, 0.5, (1, nsnps))
pop3 = np.random.binomial(1, 0.5, (1, nsnps))

#make three population and each samples from  numpy array
array1 = np.concatenate([
    np.repeat(pop1, 5, axis=0),   #repead pop1 5 times in y axis 
    np.repeat(pop2, 5, axis=0),
    np.repeat(pop3, 5, axis=0),
])    

In [5]:
array1

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 1]])

In [4]:
# generate random data
np.random.binomial(1, 0.5, (ninds, nsnps))

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 0, 1]])

In [ ]:
# ipyrad can produce an ourput called .geno
geno = "/home/deren/Documents/ipyrad/tests/analysis-ipyrad/pedic-full_outfiles/pedic-full.geno"


In [ ]:
with open(geno) as indata:
    data = indata.read()

In [ ]:
data = np.array([list(i) for i in data.split()], dtype=int)

In [ ]:
data = np.array([list(i) for i in list(10)])
data


In [ ]:
## how are we gonna code missing data? (19:05)

## how are we gonna tell it that 1 is between 0-2, these are ordered, not categorical.
# I think it is already correct. we don't need to do anything...Data are integers. If data are categoricals
#they are convered into strings

http://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html

In [ ]:
# 1. fit many clustering methods 
# 2. use cross-validation to optimize methods by splitting test-training many ways
# 3. calculate score for test data set
# 4. calculate score for 'true' taxon labels
# 5. create pretty plots


In [ ]:
# Naoko:
# 1. fit many clustering methods 
# 2. use cross-validation to optimize methods by splitting test-training many ways
# use cross-validation to optimize methods, basecally tell it to keep spreading up the data until
# do want to do that across a bunch of different models, so you have a bunch of trained models
# score them in two ways...
# 3. calculate score for test data set
how well did they perfoms on the training dataset vs test data set
# 4. calculate score for 'true' taxon labels
HOw well did they confirm with 'true' taxon labels (we have pylogenetic)
# 5. create pretty plots

# create a tool that basically allows you to take Rad seq output and run it through the program 
# and spits out something like this here is data clusted with 10 different methods. creats 10 
# different plots.


figure out how to split data

In [ ]:
# First get all of this methods to work in a notebook, or most of it at least
# Two; write a Python class object to organize your code, and make it into a package/program 
# that other people can use easily. 

In [ ]:
$ scp MyDataFile <UNI>@habaxfer.rcs.columbia.edu:<DESTINATION_PATH>

https://confluence.columbia.edu/confluence/display/rcs/Habanero+-+Working+on+Habanero




In [ ]:
KMeans
http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans

In [100]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])


In [101]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X) # if you use random_state=some_number, then you can guarantee that the output of Run 1 will be equal to the output of Run 2, i.e. your split will be always the same. 
kmeans.labels_

#third and sixed arrays are identical, therefore below third and sized values are 1

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [87]:
# kmeans = KMeans(n_clusters=3, random_state=0).fit(X) # if you use random_state=some_number, then you can guarantee that the output of Run 1 will be equal to the output of Run 2, i.e. your split will be always the same. 
# kmeans.labels_


array([0, 0, 2, 1, 1, 2], dtype=int32)

In [88]:
# kmeans = KMeans(n_clusters=4, random_state=0).fit(X) # if you use random_state=some_number, then you can guarantee that the output of Run 1 will be equal to the output of Run 2, i.e. your split will be always the same. 
# kmeans.labels_


array([3, 2, 1, 0, 0, 1], dtype=int32)

In [89]:
# kmeans = KMeans(n_clusters=5, random_state=0).fit(X) # if you use random_state=some_number, then you can guarantee that the output of Run 1 will be equal to the output of Run 2, i.e. your split will be always the same. 
# kmeans.labels_


array([3, 2, 1, 4, 0, 1], dtype=int32)

In [90]:
# kmeans = KMeans(n_clusters=6, random_state=0).fit(X) # if you use random_state=some_number, then you can guarantee that the output of Run 1 will be equal to the output of Run 2, i.e. your split will be always the same. 
# kmeans.labels_

array([3, 2, 1, 4, 0, 1], dtype=int32)

In [102]:
kmeans.predict([[0, 0], [4, 4]])

#it is saying that array [0,0] belongs to group 1, [4,4] belongs to 0


array([0, 1], dtype=int32)

In [103]:
kmeans.cluster_centers_

array([[1., 2.],
       [4., 2.]])

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans_model.labels_
metrics.silhouette_score(X, labels, metric='euclidean')

In [ ]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target

In [104]:
#kmeans.score

<bound method KMeans.score of KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)>

In [ ]:
https://doc.lagout.org/programmation/python/Learning%20scikit-learn_%20Machine%20Learning%20in%20Python%20%5BGarreta%20%26%20Moncecchi%202013-11-25%5D.pdf

Here I try an exampling from the text book

In [36]:
ninds = 30
nsnps = 5000

# generate a data set with structure
# npk: each pop consists of one row of 5000 snps (0=no, 1=yes)
pop1 = np.random.binomial(1, 0.5, (1, nsnps)) #n=1 trial, p=0.5 prob of success, size=(row=1,col=nsnps)
pop2 = np.random.binomial(1, 0.5, (1, nsnps))
pop3 = np.random.binomial(1, 0.5, (1, nsnps))

In [59]:
np.random.binomial(1, 0.5, (1, nsnps))

array([[0, 1, 0, ..., 1, 1, 1]])

In [46]:
# test
np.repeat(pop1, 5, axis=0)

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1]])

In [107]:
# test
array_test = np.concatenate([
    np.repeat(pop1, 5, axis=0),    
    np.repeat(pop2, 5, axis=0),
    np.repeat(pop3, 5, axis=0),
    ])
array_test.shape   #(15,5000) you have 15 rows (5pop1,5pop2,5pop3)

(15, 5000)

In [114]:
arraypd = pd.DataFrame(data=array_test)

In [119]:
arraypd.axes



[RangeIndex(start=0, stop=15, step=1), RangeIndex(start=0, stop=5000, step=1)]

In [106]:
# concatenate all of the points

data = pd.DataFrame({
    'array1': np.concatenate([
    np.repeat(pop1, 5, axis=0),    
    np.repeat(pop2, 5, axis=0),
    np.repeat(pop3, 5, axis=0), 
    ]),  
})

# label: first 1000 are labeled as 0, and the last 1000 are labeled as 1

data = data.sample(frac=1).reset_index(drop=True)
data.head()

TypeError: unhashable type: 'numpy.ndarray'

In [26]:
ninds = 30
nsnps = 5000

# generate a data set with structure
pop1 = np.random.binomial(1, 0.5, (1, nsnps))
pop2 = np.random.binomial(1, 0.5, (1, nsnps))
pop3 = np.random.binomial(1, 0.5, (1, nsnps))

#make three population and each samples from  numpy array
array1 = np.concatenate([
    np.repeat(pop1, 5, axis=0),    
    np.repeat(pop2, 5, axis=0),
    np.repeat(pop3, 5, axis=0),
]) 

In [73]:
array1

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0]])

In [ ]:
# how do I split train vs test set
#clustering stability
https://stats.stackexchange.com/questions/87098/can-you-compare-different-clustering-methods-on-a-dataset-with-no-ground-truth-b

In [75]:
cluster_list = list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
kmeans = KMeans(n_clusters=2, random_state=0)

In [6]:
# 2.3.9. Clustering performance evaluation

Evaluating the performance of a clustering algorithm is not as trivial as counting the number of errors or the precision and recall of a supervised classification algorithm. In particular any evaluation metric should not take the absolute values of the cluster labels into account but rather if this clustering define separations of the data similar to some ground truth set of classes or satisfying some assumption such that members belong to the same class are more similar that members of different classes according to some similarity metric.


#2.3.9.1. Adjusted Rand index
Given the knowledge of the ground truth class assignments labels_true and our clustering algorithm assignments of the same samples labels_pred, the adjusted Rand index is a function that measures the similarity of the two assignments, ignoring permutations and with chance normalization:


In [9]:

from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]
metrics.adjusted_rand_score(labels_true, labels_pred) 

0.24242424242424246

In [ ]:
#2.3.9.2. Mutual Information based scores

In [10]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

metrics.adjusted_mutual_info_score(labels_true, labels_pred) 

0.2250422831983088

#2.3.9.3. Homogeneity, completeness and V-measure
Given the knowledge of the ground truth class assignments of the samples, it is possible to define some intuitive metric using conditional entropy analysis.

In particular Rosenberg and Hirschberg (2007) define the following two desirable objectives for any cluster assignment:

homogeneity: each cluster contains only members of a single class.
completeness: all members of a given class are assigned to the same cluster.
We can turn those concept as scores homogeneity_score and completeness_score. Both are bounded below by 0.0 and above by 1.0 (higher is better):

In [13]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

metrics.homogeneity_score(labels_true, labels_pred)  

 


0.6666666666666669

In [12]:
#the higher the value the higher the completeness. labels_pred = [0, 0, 1, 1, 2, 2]
metrics.completeness_score(labels_true, labels_pred)

0.420619835714305

In [14]:
metrics.v_measure_score(labels_true, labels_pred)

0.5158037429793889

In [15]:
#all at once
metrics.homogeneity_completeness_v_measure(labels_true, labels_pred)

(0.6666666666666669, 0.420619835714305, 0.5158037429793889)

In [ ]:
#2.3.9.4. Fowlkes-Mallows scores

In [16]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

metrics.fowlkes_mallows_score(labels_true, labels_pred)  


0.47140452079103173

2.3.9.5. Silhouette Coefficient
If the ground truth labels are not known, evaluation must be performed using the model itself. The Silhouette Coefficient (sklearn.metrics.silhouette_score) is an example of such an evaluation, where a higher Silhouette Coefficient score relates to a model with better defined clusters. The Silhouette Coefficient is defined for each sample and is composed of two scores:

a: The mean distance between a sample and all other points in the same class.
b: The mean distance between a sample and all other points in the next nearest cluster.


In [17]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target

In [18]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
X.shape

(150, 4)

In [19]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
y.shape

(150,)

In [23]:
import numpy as np
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans_model.labels_
metrics.silhouette_score(X, labels, metric='euclidean')

0.5525919445213676

In [24]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [ ]:
#.3.9.6. Calinski-Harabaz Index

If the ground truth labels are not known, the Calinski-Harabaz index (sklearn.metrics.calinski_harabaz_score) can be used to evaluate the model, where a higher Calinski-Harabaz score relates to a model with better defined clusters.

In [25]:
import numpy as np
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans_model.labels_
metrics.calinski_harabaz_score(X, labels) 

560.3999242466402